version: '3.8'

services:
  mysql:
    image: 'mysql:8.0'
    container_name: echobeat-mysql
    environment:
      - 'MYSQL_DATABASE=echobeat'
      - 'MYSQL_ROOT_PASSWORD=123456789'
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - echobeat-network

  redis:
    image: 'redis:7-alpine'
    container_name: echobeat-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
    networks:
      - echobeat-network

volumes:
  mysql_data:
  redis_data:

networks:
  echobeat-network:
    driver: bridge
