server:
  port: 8081

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:mysql://localhost:3308/echobeat?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
    open-in-view: false
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# JWT 설정
jwt:
  secret:
    key: bXlTZWNyZXRLZXlGb3JEZXZlbG9wbWVudFRoYXRTaG91bGRCZUF0TGVhc3QzMkNoYXJhY3RlcnNMb25n
  access-token-expiration: 7200000  # 2시간
  refresh-token-expiration: 1209600000  # 14일

# Eureka Client 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging 설정
logging:
  level:
    com.echobeat: DEBUG
    org.springframework.security: DEBUG
