server:
  port: 8082
  
  datasource:
    url: jdbc:mysql://localhost:3308/echobeat?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

# Eureka Client 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging 설정
logging:
  level:
    com.echobeat: DEBUG

# JWT 설정
jwt:
  secret:
    key: bXlTZWNyZXRLZXlGb3JEZXZlbG9wbWVudFRoYXRTaG91bGRCZUF0TGVhc3QzMkNoYXJhY3RlcnNMb25n
  access-token-expiration: 7200000  # 2시간
  refresh-token-expiration: 1209600000  # 14일

crawler:
  user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  delay-ms: 1000
  timeout-ms: 10000

# Apple Music API 설정
apple:
  music:
    api:
      key: "${APPLE_MUSIC_API_KEY:}" # 환경변수로 설정

# 스케줄러 활성화
spring:
  application:
    name: music-service
  task:
    scheduling:
      enabled: true